### ISSUE TITLE
Better detection of poorly formed JSX (HTML)

### ISSUE THREAD

**Issue by ryansolid** [ryansolid/dom-expressions#105]
Not sure what to do yet but would be great if we could validate templates in a way that we ensure the browser won't mess with them when we instantiate them. Things like how browsers insert `<tbody>` if you omit it. Or the way certain elements aren't allowed certain children. This is critical because it breaks walks during render/hydration.

Right now I just count the tags at runtime which is super rudimentary and it only runs in dev mode since we don't want the additional code/overhead. In theory this can be done at compile time but I don't know of any existing packages. Maybe failing that we could just develop something ourselves?

**Comment by LXSMNSYC** [comment]
This principle should only apply to the templates, right?

**Comment by ryansolid** [comment]
https://github.com/MananTank/validate-html-nesting

**Comment by edemaine** [comment]
> https://github.com/MananTank/validate-html-nesting

Nice! Bundlephobia says 2.8kB minified, 1.2kB gzipped. Perhaps we could include it in dev builds, to make more helpful error messages?

**Comment by ryansolid** [comment]
I figure we'd run this at compile time so bundle size won't matter.

**Comment by LXSMNSYC** [comment]
That's one good thing, the other would be how would we validate markup that comes from components that are being appended to another markup?

For example:

```js
<h1>
  <SomeComponent />
</h1>
```

**Comment by ryansolid** [comment]
This is ok at least from our perspective. The only thing getting force fixed by the browser are the templates I think. Maybe there are exceptions still. But like the `<tbody>` doesn't happen if you just append a `<tr>`.

**Comment by LXSMNSYC** [comment]
That's true, I think the compile-time works

**Comment by ryansolid** [comment]
@orenelbaum
I used to do this but there were small differences like with quotes and escaped characters and stuff... so I just started counting tags. It's imperfect but I'd rather miss a few than have false positives.

**Comment by orenelbaum** [comment]
What matters is that the structure stays the same right? So maybe we could parse the input html and the resulting innerHTML to see if they have the same structure?

**Comment by ryansolid** [comment]
What Im getting at is adding more to runtime is probably just worst than looking at it at compile time.

**Comment by orenelbaum** [comment]
Does it matter if we run it only in dev? It seems easier to do it this way than in compile time. It would be nice in compile time to get this feedback while editing but doing it in runtime seems to me better than nothing if it's only in dev.

**Comment by ryansolid** [comment]
I should have closed this one a while ago when we added tag validation. Closing now.
