### ISSUE TITLE
How to use the Babel plugin?

### ISSUE THREAD

**Issue by elclanrs** [ryansolid/dom-expressions#11]
I couldn't find any instructions on how to use the plugin in the documentation. I tried the following:

```jsonc
// .babelrc.json
{
  "plugins": [
    "babel-plugin-jsx-dom-expressions"
  ]
}
```

And I run it with @babel/cli:

```sh
npx babel index.js -o compiled.js
```

But I keep getting a syntax error because of the JSX:

>TypeError: /home/me/library/index.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "ArrowFunctionExpression"

How do I use this with Babel?

**Comment by ryansolid** [comment]
Sorry I need a bit more context. Generally speaking you need to configure a dom-expressions runtime to work with. Which requires building it with the library of choice.

So first question is are you attempting to use this plugin with one of my libraries... like Solid, MobX-JSX, or Knockout-JSX? Or are you trying your own reactive library?

Next question, what does index.js look like? It's hard to see what this is in the dark without an idea of what you are trying to compile.

The documentation here is light mostly in that it is the specific libraries documentation that I usually rely on. I haven't streamlined the process as much as I like for people trying to write their own reactive libraries on top. So I do apologize for the lack of documentation if that is what you are after.

**Comment by elclanrs** [comment]
Actually, I figured out why it doesn't compile The error is because of my use of `ref` here:

```jsx
export default <>
  <div ref={div => {
    console.log(div);
  }}>
</>;
```

The above compiles fine with transform-syntax-jsx.

Is this error expected?

**Comment by ryansolid** [comment]
Yes.. my refs are a bit different. Although I am reviewing it. I have two types and I haven't figure out how to merge them from a compiler/runtime perspective.

There are refs which assign `ref`:

```jsx
let myVar;
<>
  <div ref={myVar}></div>
</>;
```
And ones that call functions `forwardRef`:
```
<>
  <div forwardRef={div => {
    console.log(div);
  }}></div>
</>;
```
I'm not sure how useful the first case is but the simple assignment option seems nice and sort of parallels react's `createRef` other than it's just plain JavaScript.

**Comment by elclanrs** [comment]
Thank you, I must've missed that part in the docs and just made the assumption. It'd be ideal if it takes both vars and callbacks, but I understand that may be a limitation currently.

**Comment by ryansolid** [comment]
I actually can change this. I was worried about this case:

```
function MyComp(prop) {
  return <div ref={props.ref} />
}

<MyComp />
```

If props.ref isn't passed in I can't tell if the intention is to assign it or simply it's missing. But I realized since props are readonly, even if it gets assigned who cares. It just doesn't update. Right now that scenario is compiled to:
```js
props.ref && props.ref(el)
```
I can change it to:
```js
typeof props.ref === "function" ? props.ref($el) : props.ref = $el;
```
While it is meaningless in this case if isn't passed in. This will also work for a simple ref:
```js
typeof el1 === "function" ? el1($el) : el1 = $el;
```
Overall it's more code but it only runs once on creation and I don't think it makes that much of a difference on size.
