### ISSUE TITLE
`ArrayExpression` and possibly `ObjectExpression` is treated as static for props.

### ISSUE THREAD

**Issue by LXSMNSYC** [ryansolid/dom-expressions#112]
I forgot to make an issue about this last month, this can easily be reproduced.

For expressions like

```js
<For each={[...array()]}>
```

it is compiled into

```js
each: [...array()]
```
which is like a false-positive. The hotfix would be to recursively check each item in the `ArrayExpression` to check for dynamic and static expressions. I believe `ObjectExpression` happens to behave like this.

**Comment by ryansolid** [comment]
I'm not sure I follow what the issue is?
```js
<For each={[...array()]}></For>

//compiles to:
createComponent(For, {
    get each() {
      return [...array()];
    }
})
```
Is that not right?

**Comment by LXSMNSYC** [comment]
Okay yeah I probably missed it, mb
