### ISSUE TITLE
style={undefined}

### ISSUE THREAD

**Issue by edemaine** [ryansolid/dom-expressions#121]
Is it intentional that `style={undefined}` in Solid clears all inline styles?

https://github.com/ryansolid/dom-expressions/blob/d4b76380fe65699d7d57b99df26247ddf56561f5/packages/dom-expressions/src/client.js#L110

I expected only previously set styles to be cleared, which is how `style={{}}` behaves with the current code. For point of comparison, this is how React behaves: `undefined` just clears previously set styles.

My intuition is this: In most of Solid and React, `foo={undefined}` is equivalent to omitting/removing the `foo` attribute in the HTML, which in the reactive case means undoing whatever was done by setting it. So I found it confusing that `style={undefined}` did something very different (`.style.cssText = undefined`) in Solid.

The context is that I wanted to write `style={hide() ? {display: 'none'} : undefined}` (mainly because this is easy to write as `style={display: 'none' if hide()}` in CoffeeScript), but currently I need to write `style={hide() ? {display: 'none'} : {}}`. It took me a long time to debug this, as I couldn't figure out why my style attributes set manually in an effect were getting destroyed &mdash; I didn't expect it to be relevant to the `display` setting.

For example, @mdynnl suggests a replacement function signature of
```ts
function style(node, value = {}, prev = {}) {
```

[Discord discussion](https://discord.com/channels/722131463138705510/960541284848779324)

**Comment by ryansolid** [comment]
I see. Yeah this was added later as a null check essentially because we weren't handling these sort of values before. I didn't really think about scenarios where styles were being set elsewhere. I think I was also wondering if someone went between a string and undefined if it would do the right thing. Since well a string has no really previous value to unset unless we added a bunch more code. Doing it this way seemed to be the only way to guarantee things were unset.

**Comment by edemaine** [comment]
Thanks for fixing this!  I have one possible qualm though, regarding this line:
https://github.com/ryansolid/dom-expressions/blob/b810a46464dce9e5824f26f90e0fbf49d0b95581/packages/dom-expressions/src/client.js#L114
This line changes `value` from `''` to `{}`, which will affect the string test in the next round.  Perhaps it should be
```js
value == null || (value = {});
```
?

**Comment by ryansolid** [comment]
It shouldn't be able to get there if value is a string and I was thinking there might be upside to handling false. It also does weird stuff with zero but passing a number here makes no sense. Hmm i wonder if the `== null` in the lines above is too strict.
