### ISSUE TITLE
Is `JSX.LibraryManagedAttributes` needed for anything?

### ISSUE THREAD

**Issue by trusktr** [ryansolid/dom-expressions#125]
Or can it be deleted? Unless I missed it, doesn't seem to be used for anything. 

https://github.com/ryansolid/dom-expressions/blob/8f2cd82a0fc1c5efc5c667e9284e3c273b77f6f6/packages/dom-expressions/src/jsx.d.ts#L26

**Comment by ryansolid** [comment]
No Idea what it is. I borrowed these types from others.

**Comment by trusktr** [comment]
Seems like it is not used for anything and can be removed.

**Comment by ryansolid** [comment]
Removed them. They are for default props but we don't support those.
