### ISSUE TITLE
[html] interpolating inside of an attribute causes attribute to be placed onto wrong elements, or elements to not be output

### ISSUE THREAD

**Issue by trusktr** [ryansolid/dom-expressions#131]
In this example, the attributes from the `<lume-camera-rig>` element are placed onto the root `<lume-scene>` element in the output DOM:

https://playground.solidjs.com/?hash=-1630892593&version=1.3.16

I was trying to simplify it further, but then in this simpler example the root `<lume-scene>` element is entirely removed and leaves the `<lume-node>` element as the root:

https://playground.solidjs.com/?hash=488900709&version=1.3.16

**Comment by trusktr** [comment]
Not sure what exactly triggers it yet, but if I remove all hyphens, then no DOM is output at all:

https://playground.solidjs.com/?hash=881513018&version=1.3.16

**Comment by ryansolid** [comment]
I think I know the cause. It doesn't like partial attribute interpolation. It basically follows JSX rules. This works I think: https://playground.solidjs.com/?hash=1449697475&version=1.3.16.

I never got around to adding this capability probably didn't even realize because I used it like JSX.

**Comment by trusktr** [comment]
Indeed that was it! Seems there are two separate issues. Here is one with no partial attribute interpolation, in this one no DOM outputs:

https://playground.solidjs.com/?hash=589409240&version=1.3.16

**Comment by trusktr** [comment]
I imagine that `foo="blah${blah}blah"` could be detected then treated the same as ```foo=${'blah' + blah + 'blah'}```

**Comment by trusktr** [comment]
On a similar note, I had syntax like `<div foo="${blah}>`, which has a missing quote. Perhaps it can also throw errors on unexpected syntax?
