### ISSUE TITLE
Remove `@babel/plugin-syntax-jsx`

### ISSUE THREAD

**Issue by LXSMNSYC** [ryansolid/dom-expressions#134]
- `@babel/plugin-syntax-jsx` has a weird semver for babel as peerDependency: `@babel/core@^7.0.0-0`. It will always complain regardless of the babel version.
- `@babel/plugin-syntax-jsx` is basically optional, `'jsx'` is already built into the core and can be accessed through `parserOptions`, which is what `@babel/plugin-syntax-jsx` is doing internally.

**Comment by LXSMNSYC** [comment]
I guess I'll just close this. I checked the semver and the range is fine, but not with pnpm.

**Comment by ryansolid** [comment]
Are you saying this isn't worth doing?

**Comment by LXSMNSYC** [comment]
@ryansolid I'm just thinking "maybe". TBF the plugin itself is bloatware
