### ISSUE TITLE
Fix types in CSSProperties

### ISSUE THREAD

**Issue by edemaine** [ryansolid/dom-expressions#142]
[`interface CSSProperties`](https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/jsx.d.ts#L284) is full of types like `CSSWideKeyword | any` which give some simple autocompletion but don't actually type check. The result is that `style` attributes are mostly unchecked. For example, it may appear that they accept functions wrapping reactive values, but they don't.  There's also the line `[propertyName: string]: any;` which fixes CSS variables and browser-specific overrides but also enables typos.

@LXSMNSYC suggested on Discord that [csstype](https://github.com/frenic/csstype) is a popular fix here, and we may be able to just drop it in as a replacement. But it might be a little strict; for example, I don't think CSS variables "just work" (see [overrides](https://github.com/frenic/csstype#what-should-i-do-when-i-get-type-errors)) and [values don't yet support `!important`](https://github.com/frenic/csstype/issues/160).

Alternatively, a big improvement would be replacing `any` with `string`, `string | number`, etc. as appropriate. And the CSS variable/browser override rule could be ``[propertyName: `-${string}`]: any`` so it only applies to properties starting with `-`.

**Comment by trusktr** [comment]
> and [values don't yet support `!important`](https://github.com/frenic/csstype/issues/160).

This should be easy to fix nicely with the more recent template string types I think

**Comment by trusktr** [comment]
> `` [propertyName: `-${string}`]: any `` so it only applies to properties starting with `-`.

What if, similar to how people can augment JSX, we can make some way people can augment CSS types using template string types for the CSS vars?

**Comment by edemaine** [comment]
> This should be easy to fix nicely with the more recent template string types I think

Agreed. It's mentioned as "planned" in https://github.com/frenic/csstype/issues/160#issuecomment-1143287184. A PR would probably accelerate the process though. :-)

> What if, similar to how people can augment JSX, we can make some way people can augment CSS types using template string types for the CSS vars?

Yes, this is already possible with csstype. See their description of how: https://github.com/frenic/csstype#what-should-i-do-when-i-get-type-errors
