### ISSUE TITLE
[lit-dom-expressions] better error message for `For` without a function as child

### ISSUE THREAD

**Issue by trusktr** [ryansolid/dom-expressions#158]
This example,

https://playground.solidjs.com/?hash=-945213152&version=1.4.1

throws

```
mapFn is not a function
```

. I wonder if we can improve it, f.e.

```
<For> expects a function as its only child.
```

**Comment by cheesington** [comment]
+1
Also, some mention that even whitespace around that function is not allowed.  

https://playground.solidjs.com/anonymous/145bfc4b-087e-4580-a8ba-9df4d72f7b14

**Comment by ryansolid** [comment]
If we could it'd be in solid-js. For isn't anything special. It's just following the general compilation which is correct I believe. If we could detect this it would be a runtime check.
