### ISSUE TITLE
Better handling of prototype properties in compile time or runtime

### ISSUE THREAD

**Issue by mdynnl** [ryansolid/dom-expressions#166]
Low priority bug

When using properties name e.g `toString` from object prototype in `jsx`, babel plugin can't compile them due to `Aliases`,  `PropAliases` being objects will resolve the value from prototype `Aliases['toString']` and throw. also on runtime and compile time for svg, the values from prototype will be used as prop or attribute resulting in e.g ```template(`<svg [object Object]="a"></svg>`, 2)```, or `$el['function toString() { [native code] }'] = value`.
`SVGNamespace` is similar as any propertie from prototype is considered to be a valid namespace.

The fix is to make the objects `null` prototype using `Object.assign(Object.create(null), {})` or `Object.setPrototypeOf({}, null)`. Or would `Map` be better, we already use `Set` but with `Map`  more changes are required.

**Comment by ryansolid** [comment]
Cna you give me an example of the code you write to achieve this?

**Comment by mdynnl** [comment]
<https://playground.solidjs.com/?hash=1699428709&version=1.5.5>
