### ISSUE TITLE
classList produces class="undefined" if undefined key is passed

### ISSUE THREAD

**Issue by viridia** [ryansolid/dom-expressions#168]
A common use case is a class name which is an optional parameter to a component, meaning that the parameter value will be sometimes be undefined. A component which wants to forward the class to Solid's classList needs to do something like `className={{ [forwardedClass]: true }}`, however if `forwardedClass` is undefined, then the output is `class="undefined"`.

**Comment by edemaine** [comment]
Sadly, JavaScript can't distinguish between `{ [undefined]: true }` and `{ "undefined": true }` (they are identical objects). I don't think we want to prevent a class of `"undefined"`, so this isn't solvable.

You could perhaps use `classList={{ [forwardedClass ?? '']: true }}` (which is mostly equivalent) or maybe better `classList={{ [forwardedClass]: forwardedClass }}`?

**Comment by viridia** [comment]
Actually, the workaround I am doing is to write a wrapper function that sanitizes my classList:

```
classList={classes('foo', { bar: true })}
```

```ts
export function classes(
  ...clsList: ReadonlyArray<Record<string, boolean> | string | undefined>
): Record<string, boolean> | undefined {
  let empty = true;
  let result: Record<string, boolean> = {};
  for (let cls of clsList) {
    if (typeof cls === 'string') {
      result[cls] = true;
      empty = false;
    } else if (typeof cls === 'object') {
      for (let key in cls) {
        empty = false;
        result[key] = !!cls[key];
      }
    }
  }
  return empty ? undefined : result;
}
```

**Comment by ryansolid** [comment]
It's weird I do check for "undefined" as a string: https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/client.js#L119

I didn't reproduce in the playground.https://playground.solidjs.com/?hash=1689213724&version=1.5.7

**Comment by viridia** [comment]
That is weird, I am able to reproduce it in my app just now:

```html
<button data-hk="0-0-0-0-0-0-0-0-1-0-0-1-0-0-0-0-0-1-0-0-0-0-3-2-2-1-0-0-0-0-0-0-1-1-0" class="undefined button_buttonStyle__19s29ds1 button_buttonStyle_color_default__19s29dsa">Default</button>
```

In any case, this is not super important since there are a number of ways to work around the issue.

Going forward, my suggestion is to make the `classList` API similar to clsx or the code snippet I posted earlier:

* classList would accept either an object or an array.
* If the value is an object, then the behavior is the same as it is today.
* If it is an array, then the array elements can be any of object, string, or undefined. All objects are merged, strings are appended to the list of classes, and undefined (or any falsey value) is dropped.

This would be backwards compatible with the current API. Class name forwarding would be done either by spreading or by array concatenation.

**Comment by ryansolid** [comment]
Oh this must be an SSR bug, from what I see in the output. It's fine client side as far as I can tell. 

Yeah there has been ask for array support and even some partial PRs. but the problem is every compiled features basically gets implemented in multiple places in both runtimes and both compilers so there are considerations. I worry that there is a ton of complexity here anyway. I sort of opened the door with `classList` and now I'm being much more cautious.
