### ISSUE TITLE
function voidFn() {} Question

### ISSUE THREAD

**Issue by tforward** [ryansolid/dom-expressions#181]
https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/client.js

`function voidFn() {}
`

Why tho?

**Comment by ryansolid** [comment]
Libraries are used isomorphically so sometimes people import stuff for server only and client tooling will choke on it if not there.

**Comment by tforward** [comment]
https://github.com/ryansolid/dom-expressions/blob/b2f42641eb3eef5c0455719e15bd729e14e1a778/packages/dom-expressions/src/client.js

`export {
  voidFn as Assets,
  voidFn as generateHydrationScript,
  voidFn as HydrationScript
};
`

Acts as a placeholder of sorts, returning undefined?
