### ISSUE TITLE
Update Babel to add support for Typescript 4.9

### ISSUE THREAD

**Issue by minht11** [ryansolid/dom-expressions#184]
Importing tsx files break at runtime because with the error `SyntaxError: Unexpected identifier 'satisfies' ` because satisfies operator is not properly removed.

Babel added support for it in version 7.20 https://babeljs.io/blog/2022/10/27/7.20.0

**Comment by ryansolid** [comment]
Assuming 7.20 isn't breaking wouldn't people just update their projects. Babel is just a peer dep here.

**Comment by minht11** [comment]
You are right, there are issues with npm package manager updating transitive babel dependencies, so [manually updating my lock file](https://github.com/babel/babel/issues/15157) worked. This wasn't dom-expression issue, thanks again.
