### ISSUE TITLE
The `escape()` call in `renderToString()` also escapes a `<script>`s CDATA and a JSON-stringified "state" in there that contains HTML (or any other XML-like data) is encoded unintentionally

### ISSUE THREAD

**Issue by krymel** [ryansolid/dom-expressions#196]
Hi @ryansolid ,

my SSG project experiment advances and I'm rendering a `<script>` element on server side that points to the client-side JS that is then executed by the browser on client-side. To also pass a state that userland code produces at server-side rendering time, I also add another `<script>` tag before that which contains that state serialized to JSON:

```tsx
 <script>{`var _$CTX = ${JSON.stringify(getContext(), null, 0)};`}</script>
```

At this point, the data in `_$CTX` may look like this:
```js
var _$CTX = {"id":"f12211", ... ,"props":{"someHtml":"<div><pre></pre></div>"}};
```

In the very end of the server-side processing, `renderToString` is called to serialize the DOM into a string. That string is written to the HTML file that is served statically. This is usually fine, but with the use-case above, there is one problem I just discovered and tracked down to this library: 

The implementation of `renderToString` has a call to `encode` (https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/server.js#L332)  but encode does encode the whole DOM tree which includes the CDATA of `<script>` tags. Anything could be written into CDATA of a `<script>` tag. Now usually, it doesn't break turning specific characters into HTML entities, but because the algo is lacking awareness of any kind of datatypes there, the HTML that is stored in the specific serialized state `_$CTX.props.someHtml` is also encoded. Therefore `<` turns into `&lt;` etc. pp.

Now, on client-side the code in my example tries to render `someHtml` using `<div innerHTML={props.someHtml} />` and instead of the rendered HTML, I get just a string because it now receives HTML entity encoded HTML. That's unexpected and unintended. 

I'm sure that this use-case is rather unusual... but wouldn't it be more correct in general to not encode CDATA of `<script>`? I know that to implement this will lead to a performance degradation because you'd need to implement at least one tree traversal. I implemented something like that before and found https://github.com/WebReflection/linkedom to be the fastest and memory-efficient algorithm because it implements DOM parsing/serialization as a linked list.

At the moment I'm using a workaround for now using an additional encoding layer on top, but that's just not so efficient and makes debugging less intuitive.

If skipping CDATA encoding of `<script>`s is not an option, would there be an option to export a function like `unescape` that reverses the custom `encoding` algorithm (would probably need to generate and return an serialized index map as metadata where exactly encodings have happened... kinda weird too)? The problem is, that I can't simply use "unescape all HTML entities of the content", because my content is a syntax error stacktrace (Babel) that is rendered into an HTML string. Therefore it has mixed HTML and HTML entities intentionally. This is an example:

```html
<pre tabindex="0" style="color:#e2e4e5;background-color:#282a36;"><code><span style="display:flex;"><span>  <span style="color:#ff9f43">89</span> <span style="color:#ff6ac1">|</span>   <span style="color:#ff6ac1">return</span> (\n</span></span><span style="display:flex;"><span>  <span style="color:#ff9f43">90</span> <span style="color:#ff6ac1">|</span>     &lt;<span style="color:#ff6ac1">Page</span> <span style="color:#57c7ff">title</span><span style="color:#ff6ac1">=</span><span style="color:#5af78e">&#34;index title&#34;</span>&gt;\n</span></span><span style="display:flex;"><span><span style="color:#ff6ac1">&gt;</span> <span style="color:#ff9f43">91</span> <span style="color:#ff6ac1">|</span>         &lt;<span style="color:#ff6ac1">i</span> <span style="color:#57c7ff">mg</span> <span style="color:#57c7ff">src</span><span style="color:#ff6ac1">=</span>{<span style="color:#5af78e">`data:image/png;base64,</span><span style="color:#5af78e">${</span>props.img<span style="color:#5af78e">}</span><span style="color:#5af78e">`</span>}&gt;&lt;/<span style="color:#ff6ac1">img</span>&gt;\n</span></span><span style="display:flex;"><span>     <span style="color:#ff6ac1">|</span>                                                          <span style="color:#ff6ac1">^</span>\n</span></span><span style="display:flex;"><span>  <span style="color:#ff9f43">92</span> <span style="color:#ff6ac1">|</span>         &lt;<span style="color:#ff6ac1">div</span> <span style="color:#57c7ff">class</span><span style="color:#ff6ac1">=</span>{classes.goo}&gt;index page&lt;/<span style="color:#ff6ac1">div</span>&gt;\n</span></span><span style="display:flex;"><span>  <span style="color:#ff9f43">93</span> <span style="color:#ff6ac1">|</span>         &lt;<span style="color:#ff6ac1">style</span>&gt;\n</span></span><span style="display:flex;"><span>  <span style="color:#ff9f43">94</span> <span style="color:#ff6ac1">|</span>           {props.cssFile}</span></span></code></pre>
```

Again -- thank you for all your amazing work!

edit: Maybe linkedom might be an interesting read if you don't know it yet, it guarantees:
- minimal amount of RAM needed, given any task to perform, as nothing is ever retained on RAM
- linear fast performance for any every-time-new structure, such as those created via importNode or cloneNode (i.e. template literals based libraries)
- much faster DOM manipulation, without side effect caused by cache invalidation

**Comment by ryansolid** [comment]
Yeah not doing DOM parsing. As you said it is expensive. We can probably locate script tags at compile time and tell them not to generate code that would escape their contents.
