### ISSUE TITLE
Missing `onFocus`

### ISSUE THREAD

**Issue by phungleson** [ryansolid/dom-expressions#204]
A recent commit seems to remove `onFocus` from type definition.

https://github.com/ryansolid/dom-expressions/commit/5d0b08317f0136670e3dfb9e76c9a24a20b24de1#diff-b30b26e449710cd6cdd9f82724a2ca1ac009365d41734e30b0f46a7b8aae6492L113

Let me know if I can help to add it back.

Cheers,

**Comment by ryansolid** [comment]
I think it is still there just moved.

**Comment by phungleson** [comment]
Yeah thanks, someone on Discord also pointed out.

In that case, I am not sure why my vscode didn't auto-suggest it? maybe vscode can only detect first level interface?

<img width="286" alt="image" src="https://user-images.githubusercontent.com/93457/219554963-526effa5-5f77-45c7-ac09-04c8332ad390.png">

**Comment by phungleson** [comment]
Err, I removed `node_modules` and install again, and it seems to work.

Cheers,
