### ISSUE TITLE
The delegate "addEventListener", it cannot add multiple listeners

### ISSUE THREAD

**Issue by GakkiiSmile** [ryansolid/dom-expressions#210]
and external users are easily misled into thinking that it is the same as DOM.addEventListener

**Comment by GakkiiSmile** [comment]
and I think we should also add a "removeEventListener" method.

**Comment by snnsnn** [comment]
I believe that is intentional for performance reasons. There are many ways to add multiple listeners, refs are the most common one.

https://stackoverflow.com/questions/73263711/how-to-perform-multiple-actions-when-clicking-on-a-button-component/74721079#74721079

**Comment by ryansolid** [comment]
This is internal API for JSX primarily so it is the equivalent to `.onclick` etc...
