### ISSUE TITLE
feat: add support for attr: and prop: in spread()

### ISSUE THREAD

**Issue by MarkChrisLevy** [ryansolid/dom-expressions#211]
Currently ```spread()``` and eventually ```assign()``` do not support ```attr:``` and ```prop:``` props. This cause issues when spread() is used or custom element with ```<Dynamic/>``` - basically you cannot set attributes and cannot set camelCase props:
https://playground.solidjs.com/anonymous/ef6367d8-6c4e-4ea2-856f-392de1666d6d

The change in assignProp is fairly ease, I can make appropriate PR if you agree with this.

**Comment by ryansolid** [comment]
Ok.. yeah. I was aware of this and was getting ever conscious of additions to spread/assign but these are pretty core and make sense to be present. We do need to consider them for SSR `ssrSpread` and not is the only consideration. Assigning to `prop:` for ssr basically disappears it I guess and attr is more or less a pass-through.

Does make me wonder if the decisions around handling custom elements were too premature not considering SSR sufficiently for libraries that don't follow Solid Elements convention. Well doesn't matter much for this issue.

**Comment by MarkChrisLevy** [comment]
@ryansolid Pls take a look if you agree with this solution for solving attr:/prop: and aliases issue:
https://github.com/MarkChrisLevy/dom-expressions/commit/f7750bac926415f8f496af8e29d115bcb8bb4676

The one thing I'm unsure is whether other aliases (Booleans and Properies) should also be element/tag aware - imho yes.
