### ISSUE TITLE
bug: custom element readonly prop always converted to readOnly

### ISSUE THREAD

**Issue by MarkChrisLevy** [ryansolid/dom-expressions#212]
Related to https://github.com/solidjs/solid/issues/594 - basically you cannot have a custom element with readonly prop, as it is always converted to readOnly, which is required for input element, but readOnly is not part of HTMLElement spec, only HTMLInputElement. 

https://playground.solidjs.com/anonymous/3385e30a-71ab-478f-8307-4752b1729eee

Aliasing readonly to readOnly should be made only for <input> tag.

**Comment by ryansolid** [comment]
I hear you. Right now all aliases are global so would take some rework

**Comment by MarkChrisLevy** [comment]
I can make a PR, including changes related to #211.

**Comment by MarkChrisLevy** [comment]
Fixed with #213
