### ISSUE TITLE
Bundle gets es6 syntax

### ISSUE THREAD

**Issue by aimuzov** [ryansolid/dom-expressions#216]
Hi, I've encountered a problem. My code should be in es5 standard, but the bundle gets code with es6. I started looking into why this is happening and found a line of code that adds the 'const' declaration to the bundle.

If I change it here from const to var, the problem goes away:
```diff
- path.node.body.unshift(t.variableDeclaration("const", declarators));
+ path.node.body.unshift(t.variableDeclaration("var", declarators));
```
([link to reference](https://github.com/ryansolid/dom-expressions/blob/a93e1d3ba7db28be0b59bf59239a907846025116/packages/babel-plugin-jsx-dom-expressions/src/dom/template.js#L58))

Example of code from bundle (before fix):
```js
const _tmpl$ = /*#__PURE__*/template(`<div><div></div><div></div></div>`, 6);

var ConfigOptionsPreview = function ConfigOptionsPreview(props) {
  // some code (es5)
};
```

Example of code from bundle (after fix):
```js
var _tmpl$ = /*#__PURE__*/template(`<div><div></div><div></div></div>`, 6);
// ^ the fix replace 'const' by 'var'

var ConfigOptionsPreview = function ConfigOptionsPreview(props) {
  // some code (es5)
};
```

I think this is the wrong solution to the problem, but I haven't found any other way to downgrade the standard from es6 to es5. I started researching how other babel plugins are written and noticed that they specify var instead of const/let (for example: [1](https://github.com/babel/babel/blob/b1e73d6f961065c56427ffa89c130beea8321d3b/packages/babel-helper-module-imports/src/import-builder.ts#L102), [2](https://github.com/babel/babel/blob/362451b76439ea17308c392d8c782135de0823de/packages/babel-plugin-proposal-object-rest-spread/src/index.ts#L515), [etc](https://github.com/babel/babel/search?l=TypeScript&q=variableDeclaration&type=code)...).

How to solve this problem? I can create repo for reproduce problem if needed.

babel config:
```js
module.exports = {
	// ...
	presets: [
		"solid",
		[
			"@babel/preset-env",
			{
				exclude: [
					"transform-async-to-generator",
					"transform-regenerator",
				],
			},
		],
	],
  // ...
}
```

P.S: Sorry for my bad English, it's not my native language.

**Comment by trusktr** [comment]
I think you need to set preset-env's `targets` option to the older targets you support.

**Comment by LinsRock** [comment]
> It's already setupped.

Hi, Have you solved it yet?
I had the same problem, my targets were set low enough (chrome >= 40), but the jsx template product I built still contained const

```javascript
// ...
function template(html, isCE, isSVG) {
  var node;
  var create = function create() {
    var t = document.createElement("template");
    t.innerHTML = html;
    return isSVG ? t.content.firstChild.firstChild : t.content.firstChild;
  };
  var fn = isCE ? function () {
    return untrack(function () {
      return document.importNode(node || (node = create()), true);
    });
  } : function () {
    return (node || (node = create())).cloneNode(true);
  };
  fn.cloneNode = fn;
  return fn;
}

const _tmpl$ = /*#__PURE__*/template(`<div b=2 a>`);
// ^ this
```
