### ISSUE TITLE
Cannot use `ref` for `Tagged Template`/`lit-dom-expressions`

### ISSUE THREAD

**Issue by lominming** [ryansolid/dom-expressions#226]
In JSX, we can use `ref` like `<div ref={var}...>`, is there a equivalent for tagged template so that I can get a reference to the dom element?

**Comment by ryansolid** [comment]
You can use `ref` but inly in the callback form.

Like:
```js
let ref;
html`<div ref=${el => ref = el} />` 
```
Or just pass a signal setter to it.
