### ISSUE TITLE
Spread can be problematic with SVG and the class attribute

### ISSUE THREAD

**Issue by amoutonbrady** [ryansolid/dom-expressions#24]
When using `spread` with an SVGElement, `spread` calls `spreadExpression` which in turn calls `assign`.
In the tree of possibilities in `assign` if we are spreading a `class` we end up on [that branch](https://github.com/ryansolid/dom-expressions/blob/93e1748ccaf3ad3adfa0a9ca512556369b4d8223/packages/dom-expressions/src/runtime.js#L185) because `class` is a keyword registered in the `Attributes` constant and [is of type `property`](https://github.com/ryansolid/dom-expressions/blob/93e1748ccaf3ad3adfa0a9ca512556369b4d8223/packages/dom-expressions/src/constants.js#L18).

We then arrives to this expression: [`} else node[info.alias] = value;`](https://github.com/ryansolid/dom-expressions/blob/93e1748ccaf3ad3adfa0a9ca512556369b4d8223/packages/dom-expressions/src/runtime.js#L188). I believe this is where things are a bit weird with SVG and the className attribute. I found [this stackoverflow](https://stackoverflow.com/a/37949156) about it. I believe you are doing something similar which causes the following error:

`Cannot assign to read only property 'className' of object '#<SVGSVGElement>'`

Here's a small repro: https://codesandbox.io/s/solid-svg-spreading-class-bug-vdefz?file=/src/index.tsx

Let me know if you need more details.

**Comment by ryansolid** [comment]
Yeah I need to change the order or make that block for non-SVGs only. Thanks I missed this,

**Comment by amoutonbrady** [comment]
Thank you for the quick action Ryan! Much appreciate it.
