### ISSUE TITLE
ReferenceError: ogComplete is not defined

### ISSUE THREAD

**Issue by nksaraf** [ryansolid/dom-expressions#265]
Looks like ogComplete has not been declared before use here. Also might be a hint that we are not testing the streaming anywhere.

https://github.com/ryansolid/dom-expressions/blob/a85d688353fef165b0456d5e192f4359dc00d5cb/packages/dom-expressions/src/server.js#L201C14-L201C14

**Comment by ryansolid** [comment]
This only impacts the render async flow. But yeah it wouldn't crash (outside of strict mode) but it would pollute the global namespace.
