### ISSUE TITLE
Type definitions of `classList` are wrong

### ISSUE THREAD

**Issue by danieltroger** [ryansolid/dom-expressions#279]
It doesn't return `void` as defined here https://github.com/ryansolid/dom-expressions/blob/31a05fd3f74aed26e54586c60dee4663b18acd65/packages/lit-dom-expressions/src/index.ts#L12

At least not from what the code looks like
<img width="887" alt="Screenshot 2023-10-20 at 20 30 29" src="https://github.com/ryansolid/dom-expressions/assets/4047180/903764eb-265d-40a9-aa54-f83d7b19507d">

**Comment by lxsmnsyc** [comment]
I don't think it matters much since the API is purely internal and only used by the compiler.

**Comment by danieltroger** [comment]
Why is it purely internal? It's exported by `solid-js/web`.

I used it to set classes manually and it was <i>extremely</i> handy. Basically I have a library that returns an element and I have a signal that contains classes that I want to add to that element after its creation. I don't want to modify the library/bloat the interface, so I just used classList. But it got red because it gets typechecked when it's in my actual code.

I made a PR for you so it's easier to fix :)

https://github.com/ryansolid/dom-expressions/pull/280

**Comment by lxsmnsyc** [comment]
> Why is it purely internal? It's exported by solid-js/web.
Re-exported, as the compiler would refer to the module as to where it should import, since `dom-expressions` has no true runtime. (The runtime is cloned on Solid's side)

**Comment by danieltroger** [comment]
Sorry I don't quite understand, is there another repo with this for specifically solid where I should open a pull request? How is this runtime cloned on Solid's side?

**Comment by lxsmnsyc** [comment]
@danieltroger it's okay to make a PR here. `dom-expressions` code doesn't exist in Solid's repo and exists only during bundling

**Comment by ryansolid** [comment]
I needs to be re-exported the way dom-expressions works so the compiler can find it (alias it whatever). Sort of awkward tension because yeah I don't really want to consider this stuff external API.
