### ISSUE TITLE
Don't consider namespace imports to be dynamic expression

### ISSUE THREAD

**Issue by intrnl** [ryansolid/dom-expressions#283]
This is a common pattern with CSS Modules:
```jsx
import * as styles from './style.module.css';

const template = (
  <button class={styles.button}>
    Click here
  </button>
);
```

This gets transformed into something along the lines of
```js
_$effect(() => _$className(_el, styles.button));
```

While it is inevitable that the `className` helper has to exist, ideally, `effect` shouldn't. Property access on namespaced imports are not expected to cause reactive side-effects, and should be treated as if they were individual import specifiers instead.

**Comment by intrnl** [comment]
Need to add test case for `styles[foo()]`

**Comment by lxsmnsyc** [comment]
This is actually a good idea.

**Comment by intrnl** [comment]
As much as I would want to get that working, I'm not sure if that's possible at the moment, the transformation code we have right now isn't designed to handle dynamic expressions within static templates, say, this isn't possible:

```js
const _tmpl$ = /*#__PURE__*/_$template(`<button${_$staticAttr('class', styles.button)}>Click here`);
```
