### ISSUE TITLE
`<this.Foo />` doesn't work

### ISSUE THREAD

**Issue by trusktr** [ryansolid/dom-expressions#293]
Here's a React example:

https://codesandbox.io/s/wonderful-water-6pj6xx?file=/App.js

In Solid it isn't working:

https://playground.solidjs.com/anonymous/8b30b075-a0b6-4816-b22d-cff8fdecad7e

A workaround is to read the variable off of `this` first:

https://playground.solidjs.com/anonymous/0520b3f9-bc27-4d39-b3b0-b3ea55e72b2b

**Comment by lxsmnsyc** [comment]
Let's just use #292 since it suffers from the same cause.

**Comment by trusktr** [comment]
Seems to be a different cause. In this case the output has this:

```js
_$createComponent("this".Foo, {})
```
