### ISSUE TITLE
Reference @babel/types as dependency / dev dependency

### ISSUE THREAD

**Issue by amoutonbrady** [ryansolid/dom-expressions#30]
I'm in the process of migrating every project I have related to solid to `yarn 2`. One of the good thing about `yarn 2` is that it's stricter with its module resolution and when using `babel-preset-solid` which relies on `babel-plugin-jsx-dom-expression`, it gets stuck because it can't find any reference to `@babel/types` in the `package.json` dependencies/dev dependencies despite being imported multiple times within the source code as seen in the below screenshot.

![image](https://user-images.githubusercontent.com/17355226/94270286-1d225300-ff40-11ea-8492-3e3726033ddf.png)

Would it be possible to add it or is there a specific reason for it to be missing? (or am I just blind and I missed it)

Here's the error, for reference.

```bash
[!] (plugin babel) Error: babel-plugin-jsx-dom-expressions tried to access @babel/types, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

As an alternative, I can always install it within my poject, but that's not ideal since I'm not really the one relying on it directly.

**Comment by ryansolid** [comment]
Yeah definitely. It comes as part of Babel core so I never thought about it. I wonder why Yarn is different but it'd be easy to do I imagine.

**Comment by amoutonbrady** [comment]
I believe it is used in order to optimize their cache and module resolution.

[Here](https://yarnpkg.com/features/pnp#pnp-loose-mode) is a beginning of an explanation.
[Here](https://yarnpkg.com/features/pnp#pnp-loose-mode) is pnpm (another package manager) stating it.

Anyway, thank you Ryan! :)

**Comment by ryansolid** [comment]
Ok it's fixed but I made some breaking changes so bumped minor will be updating Solid.

**Comment by amoutonbrady** [comment]
Thank you for your reactivity Ryan!
