### ISSUE TITLE
Cleanup container when call dispose

### ISSUE THREAD

**Issue by mduclehcm** [ryansolid/dom-expressions#32]
I think it's nicer if we cleanup container when user call disposer.

```js
const dispose = render(App, document.getElementById("app"));
dispose(); // exepect remove inserted component
```

https://github.com/ryansolid/dom-expressions/blob/ba1ea6b2d8136d9fcae412682ec162bc010f6c50/packages/dom-expressions/src/runtime.js#L14

**Comment by ryansolid** [comment]
It's an interesting balance. I can do that but people requested being able to not own the container. So like right now you can set the container to `document.body` and it works. I might be able to have it surgically remove itself though. I do agree it makes more sense.

**Comment by mduclehcm** [comment]
@ryansolid I agree with you that it's hard to isolate ranges. Can we use html comment to mark what elements ranges to remove?
```html
<div id="app">
  <div>other app</div>
  <!-- solid-z24h5 -->
  <div>solid app el1</div>
  <div>solid app el2</div>
  <!-- end-solid-z24h5 -->
</div>
```

**Comment by ryansolid** [comment]
Yeah technically I do track the range internally it just isn't available at the point I need. I could add this extra stuff and extra code but I don't think it's that important. Hydration needs to own the mount point etc.. It just isn't worth it to not force the extra element at the mount point.

**Comment by ryansolid** [comment]
I've added it and will be in the next release.
