### ISSUE TITLE
className is wrong when both `class` and `className` are used and one of them is `null` or `undefined`

### ISSUE THREAD

**Issue by vemoo** [ryansolid/dom-expressions#34]
[repro](https://solid-template-explorer.netlify.app/#GYVwdgxgLglg9mABAQQA6oBQEoDeAoRRCBAZykQA8BGRAXkTBABsmBuAo08igJjsXAATAKbAYYYYI4AnYVBDSkAHkEwAbkSYBDEiQByWgLbDaOagF9NOkqd7mAfEoD0qtfbzmgA)
the class name for `<div className={x1} class={x2}></div>` is transformed to `` `${x1} ${x2}` `` which is `"null undefined"` if `x1=null, x2=undefined`.

I've taken a look at https://github.com/ryansolid/dom-expressions/blob/ba1ea6b2d8136d9fcae412682ec162bc010f6c50/packages/babel-plugin-jsx-dom-expressions/src/dom/element.js#L132-L150
to see how it could be fixed, but I don't think I understand it enought to fix it.

The possible solutions I have in mind are:

- Transform it to `` `${x1 ?? ""} ${x2 ?? ""}` `` but the class name would end up having extra spaces.
- Transform it to a more complex inline expression:  `` `${(c = x1) == null ? "" : c + " "}${(c = x2) == null ? "" : c}` `` but there can also end up being an extra space at the end
- Use the `classList` runtime function or one similar to it

**Comment by vemoo** [comment]
Another issue if both `class` and `className` are literals: [repro](https://solid-template-explorer.netlify.app/#GYVwdgxgLglg9mABAQQA6oBQEpEG9GIBQBATgKZQglIA8AJjAG6IQA2AhgM6cC8AROz4sO3AHLsAtmX4AjPgD4aAegaN5hAL5A)
`<div class="a" className="b"></div>` becomes `` ` b` ``

**Comment by ryansolid** [comment]
Thanks for reporting these. I'm not sure the extra space matters enough to warrant more complicated code for what I consider an edge case. Classlist is possible but it is a runtime mechanism. The difference is the existing mechanism is based on a boolean expression. I guess it's possible to make it like `{[expr]: !!expr}` I could compile it directly I suppose but if I was going granular I'd need to know the previous value as it changes. So I think it would need the helper. Easier to accept the space for now and move on.

I see the static problem it's like I got sidetracked and didn't finish the job. I pop the previous value but forget to append to it. I will have these fixed up shortly. Thanks again.
