### ISSUE TITLE
ssr render generated script is missing`;` 

### ISSUE THREAD

**Issue by thinke5** [ryansolid/dom-expressions#344]
When ssr renders html, it generates this code
```html
<script>self.$R=self.$R||[];_$HY.r["0200001000001000001100"]="$$f"_$HY.r["02000010000010000020"]="$$f"</script>
```
The generated code is missing`;` it will cause the generated code to execute incorrectly
https://github.com/ryansolid/dom-expressions/blob/b0016751ad0149e61c93337ce10c135f3f8efe90/packages/dom-expressions/src/server.js#L20

**Comment by ryansolid** [comment]
Yeah renderToStringAsync/Stream has it but it is missing from renderToString. Good find.
