### ISSUE TITLE
when `class` or `className` is used more than once the attributes that come after are removed

### ISSUE THREAD

**Issue by vemoo** [ryansolid/dom-expressions#35]
[repro](https://solid-template-explorer.netlify.app/#GYVwdgxgLglg9mABAQQA6oBQEpEG9GIBQBATgKZQglIA8AJjAG4EQA2AhgM6cC8AROz6I2XXnwBGQxJygBPVmR65cAW3YkA5jDAAuPgEYyKvgF8TiGHX7A4cPgD4aAegaN7hE0A)

the problematic code is:
https://github.com/ryansolid/dom-expressions/blob/ba1ea6b2d8136d9fcae412682ec162bc010f6c50/packages/babel-plugin-jsx-dom-expressions/src/dom/element.js#L148

i think it should be ` i && attributes.splice(classAttributes[i].key, 1);` 
but that doesn't fully fix it, with that change if there are multiple attributes only one goes missing.

**Comment by ryansolid** [comment]
Yeah it is a combination of that change and the fix from #34 seems to fix it.
