### ISSUE TITLE
Possible typo in style helper

### ISSUE THREAD

**Issue by Jager567** [ryansolid/dom-expressions#51]
https://github.com/ryansolid/dom-expressions/blob/ad095a10233455439bb72625a4f889b67990eedf/packages/dom-expressions/src/client.js#L97-L101

In various places in the helper you use `prev[s]`, suggesting that the key of `prev` should be a css property name. However, in line 100 you're using the property value as key. To me, that looks like a typo...

**Comment by ryansolid** [comment]
Yep completely.. I can see why this one got through since missing from previous just means extra work, but still works. Thanks.
