### ISSUE TITLE
Unclear way of indicating attributes

### ISSUE THREAD

**Issue by chris-czopp** [ryansolid/dom-expressions#52]
As per README:

> All attributes are props (so use className) and to indicate attributes wrap in 'attrs' object

I did:

```javascript
h('label', { attrs: { for: 'someId' } })
```

but it doesn't create attributes, instead leaves `attrs` prop with the stringified object. Can we clarify it?

**Comment by ryansolid** [comment]
Thanks for pointing this else. Made big changes to the core a while re-using the same code for spread here.. And `attrs` went with it. By default Solid uses attributes now instead of props. I will clean up the docs.
