### ISSUE TITLE
Question: What is the owner for?

### ISSUE THREAD

**Issue by Exelord** [ryansolid/dom-expressions#56]
Hi Ryan,

I am digging through the code, learning and trying understand things. Would you mind sharing a bit what is the purpose of having owner attached to elements in rendering context? :) 

https://github.com/ryansolid/dom-expressions/blob/dde0d8fe19e16a89e69ea1d48265bda032b0188e/packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/customElements/output.js#L19

**Comment by ryansolid** [comment]
Custom elements can update asynchronously. Which means the connected callback can happen outside of normal reactive flow. This was so those could still tap into it. I create nested reactive roots with it as the owner.

I use it for Solid's Context API.

**Comment by Exelord** [comment]
Oh, got it :) Thanks for the explanation Ryna. So it is totally optional, just for 3rd party support.
