### ISSUE TITLE
Reasoning for string template literals

### ISSUE THREAD

**Issue by nicketson** [ryansolid/dom-expressions#58]
Is there a reason that template literals are generated here instead of regular strings? Unless I am missing something there are never any expressions in the strings.

**Comment by ryansolid** [comment]
Can you be more more specific on where you mean by "here"?

**Comment by nicketson** [comment]
Oops, forgot to include this: https://github.com/ryansolid/dom-expressions/blob/master/packages/babel-plugin-jsx-dom-expressions/src/dom/template.js#L50

**Comment by ryansolid** [comment]
You will probably think this is silly but just avoided having extra escape characters around attribute quotes. I haven't witnessed any perf issues with template literals (tagged template literals is another thing). Although to be fair I only ever tested this with interpolation so it is possible simple string creation is different but it reads nicer and is fewer characters.
