### ISSUE TITLE
bug: renderToNodeStream fn throws error if resource resolves to `undefined`

### ISSUE THREAD

**Issue by jorroll** [ryansolid/dom-expressions#71]
When implementing a function like the one discussed in [Solid Discussions #451](https://github.com/solidui/solid/discussions/451), I noticed that [this line](https://github.com/ryansolid/dom-expressions/blob/f57b6164806557e8236b0116426fd3697b70c0b1/packages/dom-expressions/src/server.js#L55) results in an error being thrown if the resource promise resolves to `undefined` (i.e. `method "replace" doesn't exist on type undefined`). Returning an empty string seems to be a simple work-around.

I'm using the setup provided by `solid-start`. The error isn't always triggered, but is generally triggered if you reload the page (I don't think it's triggered by hot module reloading).

**Comment by ryansolid** [comment]
Good call I didn't really it didn't end up with a string in that case. I will get that fixed up.

**Comment by jorroll** [comment]
Ya I didn't realize that `JSON.stringify(undefined)` returns `undefined` either.
