### ISSUE TITLE
Camel Case vs Kebab Case for CSSProperties

### ISSUE THREAD

**Issue by jcuenod** [ryansolid/dom-expressions#72]
I was expecting to use camel case for CSS property styles in Solid (probably because of React). I'm not sure if this is documented anywhere but I just wanted to note it. I'm assuming you've given this consideration already but I'd be curious to hear your rationale...

**Comment by ryansolid** [comment]
For sure: https://github.com/solidjs/solid/issues/143

I decided to go with just one option for slimness. But using the `setProperty` API has some nice benefits.

**Comment by jcuenod** [comment]
Thanks, I remember reading that now... much appreciated!

**Comment by jcuenod** [comment]
Something I realised about this: I think the type definitions are fine with camelCased properties but not with kebab-case properties so I'm getting wrong suggestions and linter "support" as a result.

**Comment by ryansolid** [comment]
Hmm.. I'm pretty sure my types are all dashed. https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/jsx.d.ts#L260

Checked in my IDE and only saw dashed.
