### ISSUE TITLE
Consider css binding that converts styles to classes dynamically

### ISSUE THREAD

**Issue by ryansolid** [ryansolid/dom-expressions#8]
Thinking of css in js type scenarios but built into the compiler... very much like css prop in those libraries.

**Comment by yuens1002** [comment]
can you describe a use case for this? to me, if an author intended to have inline styles in the markup, it would be how he/she expects after the JSX compilation.  

are you thinking about some sort of _styleToCss_ prop like

```
<div styleToCss={name: 'div1',  styles: { backgroundColor: 'blue', fontSize: '16px' }} />
```

then compile it down to something like 
```
...

<style type="text/css">
   .div1 {
      background-color: blue;
      font-size: 16px;
   }
</styles>

...

<div class="div1" />
```

**Comment by ryansolid** [comment]
That's what I was originally thinking. Although recently I've been impressed with styled-jsx which is closer to the approach Vue and Svelte take. I think it is more likely I go that way. Using template scoped styled tags. Allowing the styles to be applied simply by string name. styled-jsx also supports dynamic styles too. So it sort of does all the things I personally like:

1. Simple string styles in the JSX on each element
2. Familiar CSS syntax
3. Supports Dynamic Styles driven by JavaScript (ie.. shared vars are in the JavaScript)

**Comment by yuens1002** [comment]
personally, special tags like <jsx styles>...</ jsx styles> inside _JSX_ ends up clustering readability.  One of those things i wish react supports is a single file component structure like vue or svelte. so if you're thinking about going that route, i think there's value in that.

**Comment by ryansolid** [comment]
Yeah which makes it tricky because everyone has a different preference. Single page files are possible(there was some discussion in the old repo) but unlikely since I like the dynamic nature of JSX, multi Component partials etc. JSX doesn't prevent from putting everything in the same file, but it also lets you do infinitely more. Ultimately they put a lot of importance on the Components which are just ephemeral function calls the way this library works.

When it comes to dynamic styles right now as far I see it you have 3 options:
1. Handle it at the binding level. CSS prop.
Pros: Simple, with direct visible correlation.
Cons: Makes the bindings heavier so clutters view. Also creates inconsistency around cascading styles strings vs objects. Retaining style name information requires compiler tricks or even more verbosity

Technically you can hoist these bindings out of the view by wrapping in functions but end result is a lot of verbosity.

2. Styled Components
Pros: Good style isolation. Keeps views simple. Natural model for cascade.
Cons: Innately less performant. Breaks apart template cloning. Requires Component overhead and reactive prop hijacking.

3. Scoped Style Tag
Pros: Keeps template intact without heavy bindings.
Cons: Hardest to implement as leverages compiler. Scope is template level not Component level can be confusing.

You can hoist the content of the style tag out of the Component even into another JS file same way you can for CSS prop, but style element needs to stay in place. 

I'm most interested in 3 might allow to leverage compiler in an optimized way. But will take a lot more work. 1 & 2 are more or less available to anyone without compilation today.

**Comment by yuens1002** [comment]
i guess i'm not sure about what it solves over what *styles={{  color:
myBlueTone, ... }}* does already in a JSX element. in about a year of
writing React daily, there is not a single instance in my use case i needed
to <style jsx> that className or style do already out of the box.

**Comment by ryansolid** [comment]
Yeah I mean the whole dynamic class vs inline styles is a discussion too. Popularity of dynamic scoped css options is the only reason this is even a thing. Right now these libraries work fine with the Style Prop, Local CSS/Post CSS (with Sass or whatever), Emotion `css` or `styled`. The only thing I don't offer here is a compatible compiled solution. Compiled solutions for typical JSX don't work here.

**Comment by yuens1002** [comment]
Forgive me. I definitely need to play with Solid more to figure out what
common framework features are supported or lacks. What would be a minium
viable solution? Dynamic scoped styles compilation?

**Comment by ryansolid** [comment]
It's more that most css solutions are library independent so they can be used as is or with minimal wrappers. So from that perspective the minimum is do nothing in the library since there are plenty of options. React has never had an official solution here and done perfectly well. However in the past 3 years or so these JS in CSS solutions have gained more attention.

I do find it interesting the more extensive frameworks have been going this almost web component-esque style tag approach. Vue and Svelte have it built in, Next(React) uses styled-jsx. So while I don't consider this high priority if enough time goes by I will likely be working on solutions in these areas to just take the approach further.

**Comment by ryansolid** [comment]
I have figured out that it's possible to use Styled JSX as is with these libraries. I ported something for Solid. I think with that option I've got my bases covered. I might consider throwing in on this at some point but I think it just got much lower priority.
