### ISSUE TITLE
path is undfined in babel plugin / ssr

### ISSUE THREAD

**Issue by camme** [ryansolid/dom-expressions#81]
In one of our projects that uses babel-jsx-dom-expressions, we are getting a crash due to path not begin defined.
I looked at the code and it seems that ```path``` is used in a function but its never sent as an argument.

```javascript
function transformClasslistObject(expr, values, quasis) {
  expr.properties.forEach((prop, i) => {
    const isLast = expr.properties.length - 1 === i;
    let key = prop.key;
    if (t.isIdentifier(prop.key) && !prop.computed) key = t.stringLiteral(key.name);
    else if (prop.computed) {
      registerImportMethod(path, "escape"); <-------------------- this is where path is not defined
...
```

The line of code is here: https://github.com/ryansolid/dom-expressions/blob/main/packages/babel-plugin-jsx-dom-expressions/src/ssr/element.js#L355

From what I can see, the function ```transformClasslistObject``` is only used twice in the file and it would be easy to pass the ```path``` argument to it, but since I'm not familiar enough with the code, I might miss something crucial. I would otherwise submit a pull request.

Cheers and thank you!

**Comment by ryansolid** [comment]
Thanks I missed that one somehow. Must be missing the test case.
