### ISSUE TITLE
ssrStyle doesn't handle undefined

### ISSUE THREAD

**Issue by paulcmmrclly** [ryansolid/dom-expressions#83]
SSR breaks when I pass `undefined` to a html components `style` prop because ssrStyle doesn't handle `undefined`:

https://github.com/ryansolid/dom-expressions/blob/9c416694e11042eb5d2ea196e64ef4d460398947/packages/dom-expressions/src/server.js#L206-L209

**Comment by ryansolid** [comment]
Ah yes it could use some better checks in there. Thanks for reporting.
