### ISSUE TITLE
Support for reactive prop source

### ISSUE THREAD

**Issue by lxsmnsyc** [ryansolid/dom-expressions#91]
It could be useful to support this. Currently, DX treats prop sources from spread expressions to be "static" and thus, when done this way, DX cannot reapply new props when received from sources that are reactive. Consider this SolidJS example:

```js
function Heading(props){
  return (
    <h1>
      {props.foo && `foo: ${props.foo}`}
      {props.baz && `baz: ${props.baz}`}
    </h1>
  );
}

function App() {
  const [customProps, setCustomProps] = createSignal({
    foo: 'bar',
  });
  
  function toggleToBaz() {
    setCustomProps({ baz: 'bar' });
  }
  function toggleToFoo() {
    setCustomProps({ foo: 'bar' });
  }
  
  return (
     <>
       <button type="button" onClick={toggleToBaz}>Set property to baz</button>
       <button type="button" onClick={toggleToFoo}>Set property to foo</button>
       <Heading {...customProps()} />
     </>
  );
}
```

If we treat this with same behavior with children and props, it is expected for `Heading` to behave similarly for props spreading (as is if we apply the same for libraries like React).

Currently, the only workaround is to wrap the element into an accessor:

```js
  return (
     <>
       <button type="button" onClick={toggleToBaz}>Set property to baz</button>
       <button type="button" onClick={toggleToFoo}>Set property to foo</button>
       {() => <Heading {...customProps()} />}
     </>
  );
  ```
 
 However this solution is unlikely to be known or discovered by many users, and causes the component to re-render as a whole and not patch.

This can be solved easily if, by default, elements with props spreading compiles to `createComponent` wrapped into an accessor, although this might be too naive in some cases. Another solution could be to allow `mergeProps` to receive accessor to objects.

**Comment by ryansolid** [comment]
I think the latter is correct. I was aware of this. Sort of wondering if it was necessary as obviously it adds a bit to the runtime. And I have generic and specific mergeProps handlers for this. Solid's is more sophisticated than the general one. Mostly that you can get dynamic behavior on a single object without swapping it. However, swapping is a conceivable case. Just requires a little bit of doing.
