### ISSUE TITLE
Noticed an unnecessary expression within the hydration script while watching the stream

### ISSUE THREAD

**Issue by KrofDrakula** [ryansolid/dom-expressions#95]
https://github.com/ryansolid/dom-expressions/blob/6021864cc1d521dcf3ae91b2d20f585557e9875c/packages/dom-expressions/assets/hydrationScripts.js#L4

Am I missing something or is that doubled `&& el` in the expression doubled by mistake?

**Comment by ryansolid** [comment]
Hmm.. I wonder if I can make it shorter.. it's a sneaky way to return the element. We need to check that it exists up front but we also need to return it.

**Comment by KrofDrakula** [comment]
Maybe something like:

```ts
return el?.hasAttribute?.('data-hk') ?
  el :
  lookup(
    (el.host && el.host instanceof Node) ?
      el.host :
      el.parentNode
  );
```

Unless it's for golfing purposes because of transpilation inefficiency?

**Comment by ryansolid** [comment]
Yeah I've avoided optional chaining so far. This script doesn't go through transpilation and gets output directly so any assumptions I make here affect what browsers this runs in.

**Comment by KrofDrakula** [comment]
Yeah, makes sense. 👍
